packages:
  - "."

patchedDependencies:
  wouter@3.7.1: patches/wouter@3.7.1.patch

overrides:
  tailwindcss>nanoid: 3.3.7
  "@google-cloud/storage>fast-xml-parser": 4.5.4
  "@aws-sdk/xml-builder>fast-xml-parser": 5.3.5
  protobufjs: 7.5.5
  websocket-driver: 0.7.5
