CREATE TABLE `ai_config` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ai_provider` enum('manus','openai','anthropic','google','azure','custom') NOT NULL DEFAULT 'manus',
	`openaiApiKey` text,
	`anthropicApiKey` text,
	`googleApiKey` text,
	`azureApiKey` text,
	`azureEndpoint` text,
	`customApiKey` text,
	`customEndpoint` text,
	`modelName` varchar(100),
	`temperature` decimal(3,2) DEFAULT '0.7',
	`maxTokens` int DEFAULT 2000,
	`enableChat` boolean NOT NULL DEFAULT true,
	`enableRecommendations` boolean NOT NULL DEFAULT true,
	`enableTripPlanner` boolean NOT NULL DEFAULT true,
	`enableInvestorInsights` boolean NOT NULL DEFAULT true,
	`enableAdminAnalytics` boolean NOT NULL DEFAULT true,
	`dailyUserLimit` int DEFAULT 50,
	`dailyTotalLimit` int DEFAULT 10000,
	`updatedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_config_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_conversations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`conversationType` varchar(50) NOT NULL DEFAULT 'chat',
	`title` varchar(255),
	`context` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`messageCount` int NOT NULL DEFAULT 0,
	`lastMessageAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_conversations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_messages` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`conversationId` int NOT NULL,
	`role` varchar(20) NOT NULL,
	`content` text NOT NULL,
	`tokenCount` int,
	`provider` varchar(50),
	`model` varchar(100),
	`structuredData` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_messages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_usage` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`usageType` varchar(50) NOT NULL,
	`provider` varchar(50) NOT NULL,
	`model` varchar(100),
	`inputTokens` int DEFAULT 0,
	`outputTokens` int DEFAULT 0,
	`totalTokens` int DEFAULT 0,
	`estimatedCost` decimal(10,6),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_usage_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `api_keys` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(100) NOT NULL,
	`keyHash` varchar(64) NOT NULL,
	`keyPrefix` varchar(12) NOT NULL,
	`permissions` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`expiresAt` timestamp,
	`lastUsedAt` timestamp,
	`usageCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `api_keys_id` PRIMARY KEY(`id`),
	CONSTRAINT `api_keys_keyHash_unique` UNIQUE(`keyHash`)
);
--> statement-breakpoint
CREATE TABLE `api_webhooks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`url` varchar(500) NOT NULL,
	`events` json NOT NULL,
	`secret` varchar(64),
	`isActive` boolean NOT NULL DEFAULT true,
	`lastTriggeredAt` timestamp,
	`failCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `api_webhooks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `backup_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`backup_type` enum('FULL','CRITICAL','FINANCIAL','USERS','MANUAL') NOT NULL,
	`backup_status` enum('RUNNING','COMPLETED','FAILED','PARTIAL') NOT NULL DEFAULT 'RUNNING',
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`tablesIncluded` json,
	`totalRows` int DEFAULT 0,
	`totalSizeBytes` bigint DEFAULT 0,
	`s3Url` text,
	`s3Key` varchar(500),
	`errorMessage` text,
	`errorDetails` json,
	`triggeredBy` varchar(100) DEFAULT 'system',
	`isAutomatic` boolean NOT NULL DEFAULT true,
	`expiresAt` timestamp,
	`isDeleted` boolean NOT NULL DEFAULT false,
	`notes` text,
	CONSTRAINT `backup_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `banner_views` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`bannerId` int NOT NULL,
	`userId` int NOT NULL,
	`viewedAt` timestamp NOT NULL DEFAULT (now()),
	`clicked` boolean DEFAULT false,
	`clickedAt` timestamp,
	`viewContext` varchar(50),
	`sessionId` varchar(100),
	`deviceType` varchar(50),
	CONSTRAINT `banner_views_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `banners` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`subtitle` varchar(500),
	`description` text,
	`imageUrl` text NOT NULL,
	`imageUrlMobile` text,
	`banner_type` enum('SPLASH','CHARGING','MAP','PROMOTIONAL','INFORMATIONAL') NOT NULL,
	`linkUrl` text,
	`linkType` varchar(50),
	`linkTarget` varchar(50),
	`ctaText` varchar(100),
	`startDate` timestamp,
	`endDate` timestamp,
	`targetRoles` json,
	`targetCities` json,
	`targetSubscriptionTiers` json,
	`priority` int NOT NULL DEFAULT 0,
	`displayDurationMs` int DEFAULT 5000,
	`isClosable` boolean DEFAULT true,
	`showOnce` boolean DEFAULT false,
	`banner_status` enum('DRAFT','ACTIVE','PAUSED','EXPIRED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
	`impressions` int NOT NULL DEFAULT 0,
	`clicks` int NOT NULL DEFAULT 0,
	`uniqueViews` int NOT NULL DEFAULT 0,
	`advertiserName` varchar(255),
	`advertiserContact` varchar(255),
	`campaignId` varchar(100),
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `banners_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `charger_brands` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brand` varchar(100) NOT NULL,
	`model` varchar(100) NOT NULL,
	`displayName` varchar(200) NOT NULL,
	`imageUrl` text,
	`ocppVersion` varchar(20) NOT NULL DEFAULT '1.6',
	`ocppPasswordRequired` boolean NOT NULL DEFAULT false,
	`charge_type` enum('AC','DC') NOT NULL,
	`defaultPowerKw` decimal(8,2) NOT NULL,
	`maxPowerKw` decimal(8,2),
	`minChargingCurrentA` int,
	`maxChargingCurrentA` int,
	`defaultVoltage` int,
	`phases` int DEFAULT 1,
	`supportedConnectors` json,
	`supportedMeasurands` json,
	`energyUnit` varchar(10) NOT NULL DEFAULT 'Wh',
	`supportsSoC` boolean NOT NULL DEFAULT false,
	`supportsPowerMeasurement` boolean NOT NULL DEFAULT false,
	`supportsCurrentMeasurement` boolean NOT NULL DEFAULT false,
	`supportsVoltageMeasurement` boolean NOT NULL DEFAULT false,
	`supportsRemoteStart` boolean NOT NULL DEFAULT true,
	`supportsRemoteStop` boolean NOT NULL DEFAULT true,
	`supportsReset` boolean NOT NULL DEFAULT true,
	`supportsReservation` boolean NOT NULL DEFAULT false,
	`supportsSmartCharging` boolean NOT NULL DEFAULT false,
	`supportsFirmwareUpdate` boolean NOT NULL DEFAULT false,
	`ocppConfig` json,
	`meterValueInterval` int DEFAULT 30,
	`cloudApiBaseUrl` varchar(500),
	`cloudApiAuthMethod` varchar(50),
	`cloudApiDocsUrl` varchar(500),
	`notes` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `charger_brands_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `charger_problem_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`stationId` int,
	`stationName` varchar(255),
	`connectorId` varchar(50),
	`problemType` varchar(50) NOT NULL,
	`description` text,
	`photoUrl` varchar(500),
	`status` varchar(20) NOT NULL DEFAULT 'PENDING',
	`priority` varchar(20) NOT NULL DEFAULT 'MEDIUM',
	`assignedToId` int,
	`resolution` text,
	`resolvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `charger_problem_reports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `chargers_catalog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(100) NOT NULL,
	`powerKw` decimal(8,2) NOT NULL,
	`charge_type` enum('AC','DC') NOT NULL,
	`connectorType` varchar(50) NOT NULL,
	`price` bigint NOT NULL,
	`description` text,
	`features` json,
	`imageUrl` text,
	`includesTransformer` boolean DEFAULT false,
	`cableMetersIncluded` int DEFAULT 10,
	`warrantyYears` int DEFAULT 2,
	`commissionPercent` decimal(5,2) NOT NULL DEFAULT '0.00',
	`isActive` boolean NOT NULL DEFAULT true,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `chargers_catalog_id` PRIMARY KEY(`id`),
	CONSTRAINT `chargers_catalog_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `charging_stations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ownerId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`address` varchar(500) NOT NULL,
	`city` varchar(100) NOT NULL,
	`department` varchar(100),
	`country` varchar(100) NOT NULL DEFAULT 'Colombia',
	`postalCode` varchar(20),
	`latitude` decimal(10,8) NOT NULL,
	`longitude` decimal(11,8) NOT NULL,
	`ocppIdentity` varchar(100),
	`ocppPassword` varchar(255),
	`isOnline` boolean NOT NULL DEFAULT false,
	`isPublic` boolean NOT NULL DEFAULT true,
	`isActive` boolean NOT NULL DEFAULT true,
	`operatingHours` json,
	`amenities` json,
	`images` json,
	`imageUrl` text,
	`thumbnailUrl` text,
	`contactPhone` varchar(20),
	`upmeRegistrationId` varchar(100),
	`cargameId` varchar(100),
	`chargerBrandId` int,
	`manufacturer` varchar(100),
	`model` varchar(100),
	`serialNumber` varchar(100),
	`firmwareVersion` varchar(50),
	`lastBootNotification` timestamp,
	`premiumZone` enum('A','B','C') NOT NULL DEFAULT 'C',
	`premiumZoneFee` decimal(15,2) DEFAULT '0',
	`evgreenSharePercent` decimal(5,2) NOT NULL DEFAULT '30.00',
	`investorSharePercent` decimal(5,2) NOT NULL DEFAULT '70.00',
	`hostSharePercent` decimal(5,2) NOT NULL DEFAULT '0.00',
	`maintenanceFundPercent` decimal(5,2) NOT NULL DEFAULT '5.00',
	`maintenanceFundAlertThreshold` decimal(15,2) DEFAULT '500000.00',
	`energyPurchaseCostPerKwh` decimal(10,2) NOT NULL DEFAULT '850.00',
	`hostUserId` int,
	`hostName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `charging_stations_id` PRIMARY KEY(`id`),
	CONSTRAINT `charging_stations_ocppIdentity_unique` UNIQUE(`ocppIdentity`)
);
--> statement-breakpoint
CREATE TABLE `claims` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`userName` varchar(255) NOT NULL,
	`transactionId` int NOT NULL,
	`category` varchar(50) NOT NULL,
	`description` text NOT NULL,
	`requestedAmount` decimal(12,2),
	`status` varchar(30) NOT NULL DEFAULT 'PENDING',
	`resolvedByAdminId` int,
	`resolvedByAdminName` varchar(255),
	`resolution` text,
	`refundId` int,
	`resolvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `claims_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `crowdfunding_participations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`investorId` int NOT NULL,
	`amount` bigint NOT NULL,
	`participationPercent` decimal(6,4) NOT NULL,
	`paymentStatus` enum('PENDING','COMPLETED','FAILED','REFUNDED') NOT NULL DEFAULT 'PENDING',
	`paymentDate` timestamp,
	`paymentReference` varchar(255),
	`contractSigned` boolean NOT NULL DEFAULT false,
	`contractSignedAt` timestamp,
	`contractUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `crowdfunding_participations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `crowdfunding_projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`city` varchar(100) NOT NULL,
	`zone` varchar(255) NOT NULL,
	`address` varchar(500),
	`targetAmount` bigint NOT NULL,
	`raisedAmount` bigint NOT NULL DEFAULT 0,
	`minimumInvestment` bigint NOT NULL DEFAULT 50000000,
	`totalPowerKw` int NOT NULL DEFAULT 480,
	`chargerCount` int NOT NULL DEFAULT 4,
	`chargerPowerKw` int NOT NULL DEFAULT 120,
	`hasSolarPanels` boolean NOT NULL DEFAULT true,
	`estimatedRoiPercent` decimal(5,2) DEFAULT '85.00',
	`estimatedPaybackMonths` int DEFAULT 14,
	`status` enum('DRAFT','OPEN','IN_PROGRESS','FUNDED','BUILDING','OPERATIONAL','CLOSED') NOT NULL DEFAULT 'DRAFT',
	`targetDate` timestamp,
	`launchDate` timestamp,
	`fundedDate` timestamp,
	`operationalDate` timestamp,
	`priority` int NOT NULL DEFAULT 0,
	`spaceSubmissionId` int,
	`stationId` int,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `crowdfunding_projects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `event_guests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20),
	`company` varchar(255),
	`position` varchar(255),
	`qrCode` varchar(100) NOT NULL,
	`investment_package` enum('AC','DC_INDIVIDUAL','COLECTIVO'),
	`investmentAmount` bigint,
	`founderSlot` int,
	`event_guest_status` enum('INVITED','CONFIRMED','CHECKED_IN','NO_SHOW','CANCELLED') NOT NULL DEFAULT 'INVITED',
	`invitationSentAt` timestamp,
	`invitationEmailId` varchar(255),
	`checkedInAt` timestamp,
	`checkedInBy` int,
	`userId` int,
	`notes` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `event_guests_id` PRIMARY KEY(`id`),
	CONSTRAINT `event_guests_qrCode_unique` UNIQUE(`qrCode`)
);
--> statement-breakpoint
CREATE TABLE `event_payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`guestId` int NOT NULL,
	`amount` bigint NOT NULL,
	`reservationDeposit` bigint NOT NULL DEFAULT 1000000,
	`event_payment_status` enum('PENDING','PAID','PARTIAL','REFUNDED') NOT NULL DEFAULT 'PENDING',
	`paymentMethod` varchar(50),
	`paymentReference` varchar(255),
	`wompiTransactionId` varchar(255),
	`selected_package` enum('AC','DC_INDIVIDUAL','COLECTIVO') NOT NULL,
	`founderBenefits` boolean NOT NULL DEFAULT true,
	`founderDiscount` decimal(5,2) DEFAULT '5.00',
	`zoneFeeFree` boolean DEFAULT true,
	`registeredById` int,
	`paidAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `event_payments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `evses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int NOT NULL,
	`evseIdLocal` int NOT NULL,
	`connectorId` int NOT NULL DEFAULT 1,
	`connector_type` enum('TYPE_1','TYPE_2','CCS_1','CCS_2','CHADEMO','TESLA','GBT_AC','GBT_DC') NOT NULL,
	`charge_type` enum('AC','DC') NOT NULL,
	`powerKw` decimal(8,2) NOT NULL,
	`maxVoltage` int,
	`maxAmperage` int,
	`connector_status` enum('AVAILABLE','PREPARING','CHARGING','SUSPENDED_EVSE','SUSPENDED_EV','FINISHING','RESERVED','UNAVAILABLE','FAULTED') NOT NULL DEFAULT 'UNAVAILABLE',
	`lastStatusUpdate` timestamp NOT NULL DEFAULT (now()),
	`currentTransactionId` int,
	`currentUserId` int,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `evses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `favorite_stations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`stationId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `favorite_stations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `financial_settlements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`settlement_period_type` enum('WEEKLY','MONTHLY','QUARTERLY') NOT NULL,
	`grossRevenue` bigint NOT NULL DEFAULT 0,
	`totalSessions` int NOT NULL DEFAULT 0,
	`totalKwh` decimal(12,4) DEFAULT '0',
	`totalFixedExpenses` bigint NOT NULL DEFAULT 0,
	`netRevenue` bigint NOT NULL DEFAULT 0,
	`totalEnergyCost` bigint NOT NULL DEFAULT 0,
	`energyCostPerKwh` decimal(10,2) DEFAULT '850.00',
	`revenueFromEnergy` bigint NOT NULL DEFAULT 0,
	`revenueFromPenalties` bigint NOT NULL DEFAULT 0,
	`revenueFromReservations` bigint NOT NULL DEFAULT 0,
	`revenueFromAdvertising` bigint NOT NULL DEFAULT 0,
	`investorSharePercent` decimal(5,2) NOT NULL DEFAULT '70.00',
	`platformSharePercent` decimal(5,2) NOT NULL DEFAULT '30.00',
	`hostSharePercent` decimal(5,2) NOT NULL DEFAULT '0.00',
	`investorTotalAmount` bigint NOT NULL DEFAULT 0,
	`platformTotalAmount` bigint NOT NULL DEFAULT 0,
	`hostTotalAmount` bigint NOT NULL DEFAULT 0,
	`maintenanceFundPercent` decimal(5,2) NOT NULL DEFAULT '5.00',
	`maintenanceFundAmount` bigint NOT NULL DEFAULT 0,
	`platformNetAmount` bigint NOT NULL DEFAULT 0,
	`contingencyReserve` bigint NOT NULL DEFAULT 0,
	`waterfallBreakdown` json,
	`settlement_status` enum('DRAFT','APPROVED','DISTRIBUTED','CLOSED') NOT NULL DEFAULT 'DRAFT',
	`approvedBy` int,
	`approvedAt` timestamp,
	`distributedAt` timestamp,
	`notes` text,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financial_settlements_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `firmware_updates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`station_id` int NOT NULL,
	`ocpp_identity` varchar(255) NOT NULL,
	`file_name` varchar(500) NOT NULL,
	`file_size` int NOT NULL,
	`file_url` text NOT NULL,
	`version` varchar(100),
	`status` varchar(50) NOT NULL DEFAULT 'PENDING',
	`progress` int NOT NULL DEFAULT 0,
	`error_message` text,
	`notes` text,
	`initiated_by` int,
	`started_at` timestamp,
	`completed_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `firmware_updates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `id_tags` (
	`id` int AUTO_INCREMENT NOT NULL,
	`id_tag` varchar(50) NOT NULL,
	`user_id` int,
	`id_tag_type` enum('APP','RFID','NFC','REMOTE') NOT NULL DEFAULT 'APP',
	`id_tag_status` enum('ACTIVE','BLOCKED','EXPIRED','LOST') NOT NULL DEFAULT 'ACTIVE',
	`label` varchar(100),
	`serial_number` varchar(100),
	`expires_at` timestamp,
	`parent_id_tag` varchar(50),
	`max_active_transactions` int DEFAULT 1,
	`last_used_at` timestamp,
	`last_used_station_id` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `id_tags_id` PRIMARY KEY(`id`),
	CONSTRAINT `id_tags_id_tag_unique` UNIQUE(`id_tag`)
);
--> statement-breakpoint
CREATE TABLE `investor_leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`spaceId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20),
	`interestedAmount` bigint,
	`message` text,
	`lead_status` enum('new','contacted','converted','discarded') NOT NULL DEFAULT 'new',
	`adminNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `investor_leads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `investor_payouts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`investorId` int NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`totalRevenue` decimal(14,2) NOT NULL,
	`investorShare` decimal(14,2) NOT NULL,
	`platformFee` decimal(14,2) NOT NULL,
	`investorPercentage` int NOT NULL DEFAULT 70,
	`transactionCount` int NOT NULL,
	`totalKwh` decimal(12,4) NOT NULL,
	`bankName` varchar(100),
	`bankAccount` varchar(100),
	`accountHolder` varchar(255),
	`accountType` varchar(50),
	`status` enum('PENDING','REQUESTED','APPROVED','PROCESSING','PAID','REJECTED') NOT NULL DEFAULT 'PENDING',
	`requestedAt` timestamp,
	`approvedAt` timestamp,
	`approvedBy` int,
	`paidAt` timestamp,
	`paymentMethod` varchar(50),
	`paymentReference` varchar(100),
	`investorNotes` text,
	`adminNotes` text,
	`rejectionReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `investor_payouts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `investor_settlement_shares` (
	`id` int AUTO_INCREMENT NOT NULL,
	`settlementId` int NOT NULL,
	`investorUserId` int NOT NULL,
	`participationPercent` decimal(8,4) NOT NULL,
	`grossShare` bigint NOT NULL,
	`expenseShare` bigint NOT NULL DEFAULT 0,
	`netShare` bigint NOT NULL,
	`investor_share_status` enum('PENDING','CREDITED','PAID') NOT NULL DEFAULT 'PENDING',
	`creditedAt` timestamp,
	`paymentReference` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `investor_settlement_shares_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `local_auth_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`listId` int NOT NULL,
	`stationId` int NOT NULL,
	`idTag` varchar(50) NOT NULL,
	`idTagRefId` int,
	`auth_status` enum('Accepted','Blocked','Expired','ConcurrentTx') NOT NULL DEFAULT 'Accepted',
	`expiryDate` timestamp,
	`isMasterCard` boolean NOT NULL DEFAULT false,
	`label` varchar(100),
	`addedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `local_auth_entries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `local_auth_lists` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int NOT NULL,
	`listVersion` int NOT NULL DEFAULT 0,
	`chargerListVersion` int DEFAULT 0,
	`local_auth_list_status` enum('SYNCED','PENDING','FAILED','OUTDATED') NOT NULL DEFAULT 'PENDING',
	`lastSyncAt` timestamp,
	`lastSyncResult` varchar(50),
	`offline_policy` enum('LOCAL_LIST_ONLY','FREE_VENDING','REJECT_ALL') NOT NULL DEFAULT 'LOCAL_LIST_ONLY',
	`entryCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `local_auth_lists_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maintenance_fund_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int NOT NULL,
	`maintenance_fund_type` enum('deposit','withdrawal') NOT NULL,
	`amount` bigint NOT NULL,
	`description` text NOT NULL,
	`maintenanceType` varchar(100),
	`maintenanceDetail` text,
	`technicianName` varchar(255),
	`invoiceNumber` varchar(100),
	`settlementId` int,
	`balanceAfter` bigint NOT NULL DEFAULT 0,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `maintenance_fund_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maintenance_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scheduleId` int NOT NULL,
	`stationId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`maintenanceType` varchar(100) NOT NULL,
	`dueDate` timestamp NOT NULL,
	`scheduledDate` timestamp,
	`completedDate` timestamp,
	`assignedTechnicianId` int,
	`maintenance_task_status` enum('pending','in_progress','completed','overdue','cancelled') NOT NULL DEFAULT 'pending',
	`completionNotes` text,
	`actualCostCop` bigint DEFAULT 0,
	`fundRecordId` int,
	`qualityRating` int,
	`ratingNotes` text,
	`ratedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `maintenance_tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `maintenance_tickets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int NOT NULL,
	`evseId` int,
	`technicianId` int,
	`reportedById` int,
	`title` varchar(255) NOT NULL,
	`description` text,
	`priority` varchar(20) DEFAULT 'MEDIUM',
	`category` varchar(50),
	`maintenance_status` enum('PENDING','IN_PROGRESS','COMPLETED','CANCELLED') NOT NULL DEFAULT 'PENDING',
	`scheduledDate` timestamp,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`resolution` text,
	`partsUsed` json,
	`laborCost` decimal(12,2),
	`totalCost` decimal(12,2),
	`attachments` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `maintenance_tickets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meter_values` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`transactionId` int NOT NULL,
	`evseId` int NOT NULL,
	`timestamp` timestamp NOT NULL,
	`energyKwh` decimal(12,4),
	`powerKw` decimal(8,2),
	`voltage` decimal(6,2),
	`current` decimal(6,2),
	`soc` int,
	`temperature` decimal(5,2),
	`context` varchar(50),
	`measurand` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `meter_values_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`message` text NOT NULL,
	`type` varchar(50) NOT NULL,
	`referenceId` int,
	`referenceType` varchar(50),
	`isRead` boolean NOT NULL DEFAULT false,
	`readAt` timestamp,
	`pushSent` boolean DEFAULT false,
	`pushSentAt` timestamp,
	`data` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `notifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ocpp_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int,
	`ocppIdentity` varchar(100) NOT NULL,
	`ocpp_alert_type` enum('DISCONNECTION','ERROR','FAULT','OFFLINE_TIMEOUT','BOOT_REJECTED','TRANSACTION_ERROR') NOT NULL,
	`ocpp_alert_severity` enum('info','warning','critical') NOT NULL,
	`title` varchar(255) NOT NULL,
	`message` text NOT NULL,
	`payload` json,
	`acknowledged` boolean NOT NULL DEFAULT false,
	`acknowledgedAt` timestamp,
	`acknowledgedBy` int,
	`resolvedAt` timestamp,
	`autoResolved` boolean NOT NULL DEFAULT false,
	`resolvedReason` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ocpp_alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ocpp_logs` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`stationId` int,
	`ocppIdentity` varchar(100),
	`direction` varchar(10) NOT NULL,
	`messageType` varchar(50) NOT NULL,
	`messageId` varchar(100),
	`payload` json,
	`errorCode` varchar(50),
	`errorDescription` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ocpp_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `offline_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int NOT NULL,
	`ocppTransactionId` varchar(100),
	`idTag` varchar(50),
	`connectorId` int,
	`meterStart` decimal(12,4),
	`meterEnd` decimal(12,4),
	`startTimestamp` timestamp,
	`endTimestamp` timestamp,
	`reconciled` boolean NOT NULL DEFAULT false,
	`reconciledAt` timestamp,
	`reconciledTransactionId` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `offline_transactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `operational_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`availabilityPercent` decimal(5,2) DEFAULT '0',
	`totalUptimeHours` decimal(10,2) DEFAULT '0',
	`totalDowntimeHours` decimal(10,2) DEFAULT '0',
	`avgCriticalResponseHours` decimal(8,2) DEFAULT '0',
	`criticalTicketsCount` int DEFAULT 0,
	`criticalTicketsResolved` int DEFAULT 0,
	`platformUptimePercent` decimal(5,2) DEFAULT '99.50',
	`userSatisfactionScore` decimal(3,2) DEFAULT '0',
	`totalReviews` int DEFAULT 0,
	`billingAccuracyPercent` decimal(5,2) DEFAULT '100.00',
	`totalTransactions` int DEFAULT 0,
	`disputedTransactions` int DEFAULT 0,
	`solarGenerationPercent` decimal(5,2) DEFAULT '0',
	`solarKwhGenerated` decimal(12,4) DEFAULT '0',
	`solarKwhExpected` decimal(12,4) DEFAULT '0',
	`sla_status` enum('COMPLIANT','WARNING','BREACH') NOT NULL DEFAULT 'COMPLIANT',
	`slaBreachCount` int DEFAULT 0,
	`consecutiveBreachMonths` int DEFAULT 0,
	`penaltyApplied` varchar(100),
	`calculatedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `operational_metrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `overstay_locks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`evseId` int NOT NULL,
	`transactionId` int NOT NULL,
	`instanceId` varchar(100) NOT NULL,
	`lastHeartbeat` timestamp NOT NULL,
	`accumulatedCost` decimal(12,2) DEFAULT '0',
	`lastChargeTime` timestamp NOT NULL,
	`startedAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `overstay_locks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partner_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`company_name` text NOT NULL,
	`contact_name` text NOT NULL,
	`email` varchar(255) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`city` varchar(100),
	`current_brands` text,
	`annual_volume` varchar(100),
	`message` text,
	`partner_app_status` enum('pending','contacted','approved','rejected') NOT NULL DEFAULT 'pending',
	`created_at` bigint NOT NULL,
	`updated_at` bigint,
	CONSTRAINT `partner_applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pending_charge_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(64) NOT NULL,
	`userId` int NOT NULL,
	`stationId` int NOT NULL,
	`connectorId` int NOT NULL,
	`ocppIdentity` varchar(128) NOT NULL,
	`chargeMode` varchar(20) NOT NULL DEFAULT 'full_charge',
	`targetValue` decimal(12,2) NOT NULL DEFAULT '0',
	`estimatedCost` decimal(12,2) NOT NULL DEFAULT '0',
	`pricePerKwh` decimal(10,2) NOT NULL DEFAULT '1800',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp NOT NULL,
	`consumed` boolean NOT NULL DEFAULT false,
	CONSTRAINT `pending_charge_sessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `pending_charge_sessions_sessionId_unique` UNIQUE(`sessionId`)
);
--> statement-breakpoint
CREATE TABLE `personalized_offers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`triggerRule` varchar(100) NOT NULL,
	`discountPercent` int,
	`stationId` int,
	`validFrom` timestamp,
	`validUntil` timestamp,
	`title` varchar(200) NOT NULL,
	`message` text NOT NULL,
	`offer_status` enum('ACTIVE','REDEEMED','EXPIRED','DISMISSED') NOT NULL DEFAULT 'ACTIVE',
	`redeemedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `personalized_offers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `platform_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyName` varchar(255) DEFAULT 'Green House Project',
	`businessLine` varchar(255) DEFAULT 'Green EV',
	`nit` varchar(50),
	`contactEmail` varchar(255),
	`investorPercentage` int NOT NULL DEFAULT 70,
	`platformFeePercentage` int NOT NULL DEFAULT 30,
	`wompiPublicKey` text,
	`wompiPrivateKey` text,
	`wompiIntegritySecret` text,
	`wompiEventsSecret` text,
	`wompiTestMode` boolean NOT NULL DEFAULT true,
	`enableEnergyBilling` boolean NOT NULL DEFAULT true,
	`enableReservationBilling` boolean NOT NULL DEFAULT true,
	`enableOccupancyPenalty` boolean NOT NULL DEFAULT true,
	`notifyChargeComplete` boolean NOT NULL DEFAULT true,
	`notifyReservationReminder` boolean NOT NULL DEFAULT true,
	`notifyPromotions` boolean NOT NULL DEFAULT false,
	`upmeEndpoint` text,
	`upmeToken` text,
	`upmeAutoReport` boolean NOT NULL DEFAULT true,
	`ocppPort` int DEFAULT 9000,
	`ocppServerActive` boolean NOT NULL DEFAULT true,
	`minPricePerKwh` decimal(10,2) NOT NULL DEFAULT '400',
	`maxPricePerKwh` decimal(10,2) NOT NULL DEFAULT '2500',
	`enableDynamicPricing` boolean NOT NULL DEFAULT true,
	`defaultBasePricePerKwh` decimal(10,2) NOT NULL DEFAULT '1200',
	`defaultReservationFee` decimal(10,2) NOT NULL DEFAULT '5000',
	`defaultOverstayPenaltyPerMin` decimal(10,2) NOT NULL DEFAULT '500',
	`defaultOverstayGracePeriodMinutes` int NOT NULL DEFAULT 10,
	`defaultConnectionFee` decimal(10,2) NOT NULL DEFAULT '2000',
	`defaultPricePerKwhAC` decimal(10,2) NOT NULL DEFAULT '800',
	`defaultPricePerKwhDC` decimal(10,2) NOT NULL DEFAULT '1200',
	`enableDifferentiatedPricing` boolean NOT NULL DEFAULT true,
	`factorUtilizacionPremium` decimal(4,2) NOT NULL DEFAULT '2.00',
	`costosOperativosIndividual` int NOT NULL DEFAULT 15,
	`costosOperativosColectivo` int NOT NULL DEFAULT 10,
	`costosOperativosAC` int NOT NULL DEFAULT 15,
	`eficienciaCargaDC` int NOT NULL DEFAULT 92,
	`eficienciaCargaAC` int NOT NULL DEFAULT 95,
	`costoEnergiaRed` int NOT NULL DEFAULT 850,
	`costoEnergiaSolar` int NOT NULL DEFAULT 250,
	`precioVentaDefault` int NOT NULL DEFAULT 1800,
	`precioVentaMin` int NOT NULL DEFAULT 1400,
	`precioVentaMax` int NOT NULL DEFAULT 2200,
	`eventName` varchar(255) DEFAULT 'Gran Lanzamiento Red de Carga EVGreen',
	`eventDate` varchar(100) DEFAULT 'Por confirmar',
	`eventTime` varchar(100) DEFAULT 'Por confirmar',
	`eventVenueName` varchar(255) DEFAULT 'Por confirmar',
	`eventAddress` varchar(500) DEFAULT 'Bogotá, Colombia',
	`eventCity` varchar(100) DEFAULT 'Bogotá',
	`eventContactPhone` varchar(50),
	`eventContactEmail` varchar(255) DEFAULT 'evgreen@greenhproject.com',
	`eventGoogleMapsUrl` text,
	`eventWazeUrl` text,
	`eventDressCode` varchar(100) DEFAULT 'Business Casual',
	`eventDescription` text,
	`eventMaxGuests` int DEFAULT 30,
	`eventBgImageUrl` text,
	`alegraEmail` varchar(255),
	`alegraToken` text,
	`alegraEnabled` boolean NOT NULL DEFAULT false,
	`alegraTestMode` boolean NOT NULL DEFAULT true,
	`alegraDefaultItemId` varchar(50),
	`alegraDefaultTaxId` varchar(50),
	`alegraAutoInvoice` boolean NOT NULL DEFAULT true,
	`alegraPaymentMethodId` varchar(50),
	`alegraPaymentAccountId` varchar(50),
	`alegraResolutionNumber` varchar(100),
	`supportEmail` varchar(255) DEFAULT 'soporte@greenhproject.com',
	`supportPhone` varchar(50) DEFAULT '+573001234567',
	`supportAutoAssign` boolean NOT NULL DEFAULT true,
	`updatedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `platform_settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `price_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int NOT NULL,
	`evseId` int,
	`pricePerKwh` decimal(10,2) NOT NULL,
	`demandLevel` varchar(20) NOT NULL,
	`occupancyRate` decimal(5,2),
	`timeMultiplier` decimal(4,2),
	`dayMultiplier` decimal(4,2),
	`finalMultiplier` decimal(4,2),
	`isAutoPricing` boolean NOT NULL DEFAULT true,
	`transactionId` int,
	`recordedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `price_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `quote_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quoteId` int NOT NULL,
	`catalogItemId` int NOT NULL,
	`productName` varchar(255) NOT NULL,
	`productPowerKw` decimal(8,2) NOT NULL,
	`productChargeType` varchar(10) NOT NULL,
	`productConnector` varchar(50) NOT NULL,
	`unitPrice` bigint NOT NULL,
	`quantity` int NOT NULL DEFAULT 1,
	`lineTotal` bigint NOT NULL,
	`includesTransformer` boolean DEFAULT false,
	`cableMetersIncluded` int DEFAULT 10,
	`productImageUrl` text,
	`commissionPercent` decimal(5,2) NOT NULL DEFAULT '0.00',
	`commissionAmount` bigint NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `quote_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `quote_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`validityDays` int NOT NULL DEFAULT 30,
	`evgreenFeePercent` int NOT NULL DEFAULT 30,
	`ownerSharePercent` int NOT NULL DEFAULT 70,
	`hostSharePercent` int NOT NULL DEFAULT 0,
	`defaultEnergyCostPerKwh` int NOT NULL DEFAULT 700,
	`defaultSalePricePerKwh` int NOT NULL DEFAULT 1800,
	`defaultDailyHours` decimal(4,1) NOT NULL DEFAULT '4.0',
	`companyName` varchar(255) NOT NULL DEFAULT 'EVGreen - Green House Project S.A.S',
	`companyNit` varchar(50) NOT NULL DEFAULT '901.447.678-0',
	`companyPhone` varchar(50) NOT NULL DEFAULT '321 456 7644',
	`companyEmail` varchar(255) NOT NULL DEFAULT 'evgreen@greenhproject.com',
	`companyWebsite` varchar(255) NOT NULL DEFAULT 'www.evgreen.lat',
	`headerMessage` text,
	`footerMessage` text,
	`termsAndConditions` text,
	`exclusions` text,
	`benefitsDescription` text,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quote_settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quoteNumber` varchar(20) NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientEmail` varchar(320) NOT NULL,
	`clientPhone` varchar(50),
	`clientCompany` varchar(255),
	`clientCity` varchar(100),
	`advisorId` int NOT NULL,
	`advisorName` varchar(255),
	`quote_status` enum('DRAFT','SENT','VIEWED','ACCEPTED','REJECTED','EXPIRED') NOT NULL DEFAULT 'DRAFT',
	`subtotal` bigint NOT NULL DEFAULT 0,
	`discount` bigint DEFAULT 0,
	`total` bigint NOT NULL DEFAULT 0,
	`totalCommission` bigint DEFAULT 0,
	`validityDays` int NOT NULL DEFAULT 30,
	`expiresAt` timestamp,
	`internalNotes` text,
	`clientNotes` text,
	`publicToken` varchar(64) NOT NULL,
	`viewedAt` timestamp,
	`viewCount` int DEFAULT 0,
	`sentAt` timestamp,
	`acceptedAt` timestamp,
	`rejectedAt` timestamp,
	`pdfUrl` text,
	`evgreenSharePercent` decimal(5,2) DEFAULT '30.00',
	`investorSharePercent` decimal(5,2) DEFAULT '70.00',
	`hostSharePercent` decimal(5,2) DEFAULT '0.00',
	`projectionEnergyCostPerKwh` int DEFAULT 700,
	`projectionSalePricePerKwh` int DEFAULT 1800,
	`projectionDailyHours` decimal(4,1) DEFAULT '4.0',
	`projectionScenario` varchar(20) DEFAULT 'realistic',
	`showProjection` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotes_id` PRIMARY KEY(`id`),
	CONSTRAINT `quotes_quoteNumber_unique` UNIQUE(`quoteNumber`),
	CONSTRAINT `quotes_publicToken_unique` UNIQUE(`publicToken`)
);
--> statement-breakpoint
CREATE TABLE `refunds` (
	`id` int AUTO_INCREMENT NOT NULL,
	`transactionId` int NOT NULL,
	`userId` int NOT NULL,
	`adminId` int NOT NULL,
	`adminName` varchar(255) NOT NULL,
	`amount` decimal(12,2) NOT NULL,
	`refundType` varchar(50) NOT NULL,
	`reason` text NOT NULL,
	`claimId` int,
	`walletTransactionId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `refunds_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `reservations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`evseId` int NOT NULL,
	`userId` int NOT NULL,
	`stationId` int NOT NULL,
	`startTime` timestamp NOT NULL,
	`endTime` timestamp NOT NULL,
	`expiryTime` timestamp NOT NULL,
	`reservation_status` enum('ACTIVE','EXPIRED','CANCELLED','FULFILLED','NO_SHOW') NOT NULL DEFAULT 'ACTIVE',
	`reservationFee` decimal(10,2) DEFAULT '0',
	`noShowPenalty` decimal(10,2) DEFAULT '0',
	`isPenaltyApplied` boolean NOT NULL DEFAULT false,
	`transactionId` int,
	`ocppReservationId` int,
	`reminder30MinSent` timestamp,
	`reminder5MinSent` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `reservations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `scheduled_maintenances` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`maintenanceType` varchar(100) NOT NULL,
	`maintenance_frequency` enum('weekly','biweekly','monthly','quarterly','semiannual','annual','one_time') NOT NULL,
	`nextDueDate` timestamp NOT NULL,
	`lastCompletedDate` timestamp,
	`preferredTimeStart` varchar(5) NOT NULL DEFAULT '08:00',
	`preferredTimeEnd` varchar(5) NOT NULL DEFAULT '17:00',
	`assignedTechnicianId` int,
	`assignedEngineerId` int,
	`estimatedCostCop` bigint DEFAULT 0,
	`reminderDaysBefore` int NOT NULL DEFAULT 3,
	`reminderSent` boolean NOT NULL DEFAULT false,
	`maintenance_schedule_status` enum('active','paused','completed','cancelled') NOT NULL DEFAULT 'active',
	`notes` text,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scheduled_maintenances_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `settlement_expense_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`settlementId` int NOT NULL,
	`expenseId` int,
	`name` varchar(255) NOT NULL,
	`expense_category` enum('ENERGY','INSURANCE','CONNECTIVITY','MAINTENANCE','FIDUCIARY','TAX','CONTINGENCY','ADMIN','OTHER') NOT NULL,
	`originalAmount` bigint NOT NULL,
	`proratedAmount` bigint NOT NULL,
	`waterfallPriority` int NOT NULL,
	`isProrated` boolean NOT NULL DEFAULT false,
	`prorateFormula` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `settlement_expense_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `soc_accuracy_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`transactionId` int NOT NULL,
	`vehicleId` int,
	`manualSocStart` int NOT NULL,
	`manualBatteryCapacityKwh` float NOT NULL,
	`realKwhDelivered` float NOT NULL,
	`calculatedSocEnd` int,
	`chargerSocEnd` int,
	`batteryFullDetected` boolean NOT NULL DEFAULT false,
	`detectionMethod` varchar(50),
	`estimatedErrorKwh` float,
	`estimatedErrorSocPct` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `soc_accuracy_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `space_photos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`submissionId` int NOT NULL,
	`photoUrl` text NOT NULL,
	`photoKey` varchar(500) NOT NULL,
	`caption` varchar(255),
	`photo_type` enum('general','electrical_panel','transformer','parking_area','access_road','surroundings','other') NOT NULL DEFAULT 'general',
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `space_photos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `space_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(20) NOT NULL,
	`submitterName` varchar(255) NOT NULL,
	`submitterEmail` varchar(320) NOT NULL,
	`submitterPhone` varchar(20) NOT NULL,
	`submitterCompany` varchar(255),
	`submitterDocument` varchar(50),
	`spaceName` varchar(255) NOT NULL,
	`space_type` enum('parking','mall','gas_station','hotel','restaurant','office_building','residential','supermarket','hospital','university','airport','highway_rest','other') NOT NULL,
	`spaceTypeOther` varchar(255),
	`address` varchar(500) NOT NULL,
	`city` varchar(100) NOT NULL,
	`department` varchar(100),
	`country` varchar(100) NOT NULL DEFAULT 'Colombia',
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`availableAreaM2` decimal(10,2),
	`parkingSpots` int,
	`transformerCapacityKva` decimal(10,2),
	`hasElectricalPanel` boolean DEFAULT false,
	`electricalDistance` int,
	`hasInternet` boolean DEFAULT false,
	`operatingHoursStart` varchar(5) DEFAULT '06:00',
	`operatingHoursEnd` varchar(5) DEFAULT '22:00',
	`is24Hours` boolean DEFAULT false,
	`estimatedDailyVehicles` int,
	`estimatedEvPercent` int,
	`nearbyAttractions` text,
	`socioeconomicStratum` int,
	`additionalNotes` text,
	`space_status` enum('pending','under_review','approved','rejected','letter_sent','letter_accepted','published','funded','in_construction','operational') NOT NULL DEFAULT 'pending',
	`technicalScore` int,
	`technicalNotes` text,
	`electrical_viability` enum('viable','requires_upgrade','not_viable'),
	`accessibilityScore` int,
	`trafficPotentialScore` int,
	`evaluatedBy` int,
	`evaluatedAt` timestamp,
	`rejectionReason` text,
	`aiScore` int,
	`aiAnalysis` text,
	`aiScoredAt` timestamp,
	`letterSentAt` timestamp,
	`letterAcceptedAt` timestamp,
	`letterToken` varchar(100),
	`letterSignerName` varchar(255),
	`letterSignerDocument` varchar(50),
	`letterSignerIp` varchar(50),
	`signedLetterPdfUrl` text,
	`signedLetterPdfKey` varchar(500),
	`letterSignerUserAgent` text,
	`crowdfundingProjectId` int,
	`estimatedInvestmentCop` bigint,
	`estimatedPowerKw` int,
	`estimatedChargerCount` int,
	`recommendedChargerType` varchar(50),
	`investment_type` enum('individual','colectiva') NOT NULL DEFAULT 'individual',
	`viewCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `space_submissions_id` PRIMARY KEY(`id`),
	CONSTRAINT `space_submissions_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `station_demand_forecast` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int NOT NULL,
	`dayOfWeek` int NOT NULL,
	`hourOfDay` int NOT NULL,
	`avgSessionsPerSlot` decimal(8,4) DEFAULT '0',
	`avgOccupancyRate` decimal(5,2) DEFAULT '0',
	`avgKwhPerSlot` decimal(10,4) DEFAULT '0',
	`avgRevenuePerSlot` decimal(12,2) DEFAULT '0',
	`trend` varchar(20) DEFAULT 'STABLE',
	`trendPercent` decimal(6,2) DEFAULT '0',
	`suggestedDemandMultiplier` decimal(4,3) DEFAULT '1.000',
	`confidenceScore` int DEFAULT 0,
	`sampleSize` int DEFAULT 0,
	`lastCalculatedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `station_demand_forecast_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `station_fixed_expenses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`expense_category` enum('ENERGY','INSURANCE','CONNECTIVITY','MAINTENANCE','FIDUCIARY','TAX','CONTINGENCY','ADMIN','OTHER') NOT NULL,
	`description` text,
	`amountCop` bigint NOT NULL,
	`expense_periodicity` enum('MONTHLY','BIMONTHLY','QUARTERLY','SEMIANNUAL','ANNUAL','ONE_TIME') NOT NULL,
	`startDate` timestamp NOT NULL,
	`endDate` timestamp,
	`providerName` varchar(255),
	`contractReference` varchar(255),
	`waterfallPriority` int NOT NULL DEFAULT 5,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdBy` int NOT NULL,
	`updatedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `station_fixed_expenses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `station_reviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`station_id` int NOT NULL,
	`user_id` int NOT NULL,
	`rating` int NOT NULL,
	`comment` text,
	`owner_response` text,
	`owner_response_at` timestamp,
	`is_approved` tinyint NOT NULL DEFAULT 1,
	`is_visible` tinyint NOT NULL DEFAULT 1,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `station_reviews_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`subscription_tier` enum('FREE','BASIC','PREMIUM','ENTERPRISE') NOT NULL DEFAULT 'FREE',
	`discountPercentage` decimal(5,2) DEFAULT '0',
	`freeReservationsPerMonth` int DEFAULT 0,
	`prioritySupport` boolean DEFAULT false,
	`wompiPaymentSourceId` varchar(100),
	`wompiCardToken` varchar(100),
	`cardBrand` varchar(20),
	`cardLastFour` varchar(4),
	`cardHolderName` varchar(255),
	`monthlyAmountCents` bigint DEFAULT 0,
	`lastPaymentDate` timestamp,
	`lastPaymentReference` varchar(255),
	`failedPaymentCount` int DEFAULT 0,
	`autoRechargeEnabled` boolean NOT NULL DEFAULT false,
	`autoRechargeThreshold` int DEFAULT 10000,
	`autoRechargeAmount` int DEFAULT 20000,
	`lastAutoRechargeAt` timestamp,
	`autoRechargeFailCount` int DEFAULT 0,
	`startDate` timestamp NOT NULL,
	`endDate` timestamp,
	`nextBillingDate` timestamp,
	`isActive` boolean NOT NULL DEFAULT true,
	`cancelledAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `subscriptions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `support_agents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`isOnline` boolean NOT NULL DEFAULT false,
	`isAvailable` boolean NOT NULL DEFAULT true,
	`scheduleStart` varchar(10) DEFAULT '08:00',
	`scheduleEnd` varchar(10) DEFAULT '17:00',
	`workDays` json DEFAULT ('[1,2,3,4,5]'),
	`maxConcurrentTickets` int NOT NULL DEFAULT 5,
	`activeTicketCount` int NOT NULL DEFAULT 0,
	`lastAssignedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `support_agents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `support_messages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ticketId` int NOT NULL,
	`senderId` int NOT NULL,
	`senderRole` varchar(20) NOT NULL,
	`message` text NOT NULL,
	`attachmentUrl` text,
	`readAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `support_messages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `support_tickets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`stationId` int,
	`transactionId` int,
	`subject` varchar(255) NOT NULL,
	`description` text NOT NULL,
	`category` varchar(50),
	`priority` varchar(20) DEFAULT 'MEDIUM',
	`status` varchar(20) DEFAULT 'OPEN',
	`assignedToId` int,
	`resolution` text,
	`resolvedAt` timestamp,
	`attachments` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `support_tickets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tariff_change_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tariffId` int,
	`stationId` int,
	`changedBy` int NOT NULL,
	`changedByName` varchar(255),
	`changedByRole` varchar(50),
	`tariff_change_type` enum('CREATE','UPDATE','GLOBAL_UPDATE','DEACTIVATE') NOT NULL,
	`previousValues` json,
	`newValues` json,
	`description` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `tariff_change_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tariffs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int NOT NULL,
	`name` varchar(100) NOT NULL,
	`description` text,
	`pricePerKwh` decimal(10,2) NOT NULL,
	`pricePerMinute` decimal(10,2) DEFAULT '0',
	`pricePerSession` decimal(10,2) DEFAULT '0',
	`reservationFee` decimal(10,2) DEFAULT '0',
	`noShowPenalty` decimal(10,2) DEFAULT '0',
	`overstayPenaltyPerMinute` decimal(10,2) DEFAULT '0',
	`overstayGracePeriodMinutes` int DEFAULT 10,
	`timeBasedPricing` json,
	`autoPricing` boolean NOT NULL DEFAULT false,
	`isActive` boolean NOT NULL DEFAULT true,
	`validFrom` timestamp,
	`validTo` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tariffs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`evseId` int NOT NULL,
	`userId` int NOT NULL,
	`stationId` int NOT NULL,
	`tariffId` int,
	`ocppTransactionId` varchar(100),
	`ocppNumericTxId` int,
	`startTime` timestamp NOT NULL,
	`endTime` timestamp,
	`kwhConsumed` decimal(10,4) DEFAULT '0',
	`meterStart` decimal(12,4),
	`meterEnd` decimal(12,4),
	`energyCost` decimal(12,2) DEFAULT '0',
	`timeCost` decimal(12,2) DEFAULT '0',
	`sessionCost` decimal(12,2) DEFAULT '0',
	`overstayCost` decimal(12,2) DEFAULT '0',
	`totalCost` decimal(12,2) DEFAULT '0',
	`investorShare` decimal(12,2) DEFAULT '0',
	`platformFee` decimal(12,2) DEFAULT '0',
	`transaction_status` enum('PENDING','IN_PROGRESS','COMPLETED','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING',
	`startMethod` varchar(50),
	`stopReason` varchar(100),
	`manualSoc` int,
	`manualBatteryCapacityKwh` decimal(6,2),
	`chargeMode` varchar(20) DEFAULT 'full_charge',
	`targetValue` decimal(12,2) DEFAULT '0',
	`appliedPricePerKwh` decimal(10,2),
	`reservationId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `transactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_consumption_profile` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`totalSessions` int NOT NULL DEFAULT 0,
	`totalKwh` decimal(12,4) NOT NULL DEFAULT '0',
	`totalSpentCop` decimal(15,2) NOT NULL DEFAULT '0',
	`avgKwhPerSession` decimal(8,4) NOT NULL DEFAULT '0',
	`avgCostPerSession` decimal(12,2) NOT NULL DEFAULT '0',
	`avgSessionDurationMin` int NOT NULL DEFAULT 0,
	`monthlyAvgSpent` decimal(12,2) NOT NULL DEFAULT '0',
	`monthlyAvgKwh` decimal(10,4) NOT NULL DEFAULT '0',
	`monthlyAvgSessions` decimal(6,2) NOT NULL DEFAULT '0',
	`preferredHours` json DEFAULT ('[]'),
	`preferredDays` json DEFAULT ('[]'),
	`topStations` json DEFAULT ('[]'),
	`preferredChargeType` varchar(10),
	`preferredConnectorType` varchar(20),
	`avgChargePowerKw` decimal(8,2) DEFAULT '0',
	`typicalChargeFrequencyDays` decimal(6,2),
	`lastChargeAt` timestamp,
	`nextPredictedChargeAt` timestamp,
	`userScore` int NOT NULL DEFAULT 0,
	`scoreBreakdown` json,
	`recommendedTier` varchar(20),
	`estimatedMonthlySavingsWithUpgrade` decimal(10,2) DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_consumption_profile_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_consumption_profile_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `user_data_consents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`consent_type` enum('AI_PROFILING','MARKETING','LOCATION_HISTORY') NOT NULL,
	`granted` boolean NOT NULL,
	`policyVersion` varchar(20) NOT NULL,
	`grantedAt` timestamp,
	`revokedAt` timestamp,
	`ipAddress` varchar(45),
	`userAgent` varchar(512),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_data_consents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_debts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`transactionId` int,
	`originalAmount` decimal(12,2) NOT NULL,
	`remainingAmount` decimal(12,2) NOT NULL,
	`reason` varchar(100) NOT NULL,
	`description` text,
	`debt_status` enum('PENDING','PAID','PARTIAL','WAIVED') NOT NULL DEFAULT 'PENDING',
	`autoChargeAttempts` int NOT NULL DEFAULT 0,
	`lastAutoChargeAt` timestamp,
	`paymentReference` varchar(255),
	`paidAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `user_debts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_location_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`latitude` decimal(10,7) NOT NULL,
	`longitude` decimal(10,7) NOT NULL,
	`accuracy` decimal(8,2),
	`source` varchar(50) DEFAULT 'chat',
	`address` varchar(500),
	`city` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `user_location_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_login_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`userAgent` text,
	`ipAddress` varchar(45),
	`deviceType` varchar(20),
	`browser` varchar(100),
	`os` varchar(100),
	`location` varchar(255),
	`isActive` boolean NOT NULL DEFAULT true,
	`loginAt` timestamp NOT NULL DEFAULT (now()),
	`lastActivityAt` timestamp NOT NULL DEFAULT (now()),
	`logoutAt` timestamp,
	CONSTRAINT `user_login_sessions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_route_patterns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`originLatitude` decimal(10,7) NOT NULL,
	`originLongitude` decimal(10,7) NOT NULL,
	`originName` varchar(200),
	`originAddress` varchar(500),
	`destinationLatitude` decimal(10,7) NOT NULL,
	`destinationLongitude` decimal(10,7) NOT NULL,
	`destinationName` varchar(200),
	`destinationAddress` varchar(500),
	`frequency` int NOT NULL DEFAULT 1,
	`estimatedDistanceKm` decimal(8,2),
	`averageDurationMinutes` int,
	`typicalDepartureHour` int,
	`typicalDays` json,
	`preferredChargingStops` json,
	`lastUsed` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `user_route_patterns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_vehicles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`brand` varchar(100) NOT NULL,
	`model` varchar(100) NOT NULL,
	`year` int,
	`licensePlate` varchar(20),
	`batteryCapacityKwh` decimal(6,2),
	`rangeKm` int,
	`connectorTypes` json NOT NULL,
	`maxChargePowerKw` decimal(6,2),
	`batteryLevel` int,
	`lastBatteryUpdate` timestamp,
	`isDefault` boolean NOT NULL DEFAULT false,
	`isActive` boolean NOT NULL DEFAULT true,
	`imageUrl` text,
	`nickname` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_vehicles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`email` varchar(320),
	`phone` varchar(20),
	`birthDate` varchar(10),
	`address` varchar(500),
	`city` varchar(100),
	`loginMethod` varchar(64),
	`role` enum('staff','technician','investor','user','admin','engineer','host','comercial') NOT NULL DEFAULT 'user',
	`avatarUrl` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`idTag` varchar(20),
	`companyName` varchar(255),
	`taxId` varchar(50),
	`document_type` enum('CC','NIT','CE','PASAPORTE','TI','PEP'),
	`documentNumber` varchar(50),
	`fiscalAddress` varchar(500),
	`fiscalCity` varchar(100),
	`fiscalDepartment` varchar(100),
	`kind_of_person` enum('PERSON_ENTITY','LEGAL_ENTITY'),
	`regime` enum('SIMPLIFIED_REGIME','COMMON_REGIME','NOT_RESPONSIBLE_FOR_IVA'),
	`alegraContactId` varchar(50),
	`bankAccount` varchar(100),
	`bankName` varchar(100),
	`investorTypes` json DEFAULT ('[]'),
	`investor_type` enum('individual','collective','founder'),
	`isFounder` boolean DEFAULT false,
	`founderTitle` varchar(100),
	`founderOrder` int,
	`investorPhotoUrl` text,
	`investorQuote` varchar(500),
	`investorBio` text,
	`investorBadge` varchar(50),
	`investorJoinedAt` timestamp,
	`investorTotalInvested` bigint DEFAULT 0,
	`investorShowInWall` boolean DEFAULT true,
	`technicianLicense` varchar(100),
	`assignedRegion` varchar(100),
	`fcmToken` text,
	`fcmTokenUpdatedAt` timestamp,
	`pushSubscription` text,
	`notifyChargingComplete` boolean DEFAULT true,
	`notifyLowBalance` boolean DEFAULT true,
	`notifyPromotions` boolean DEFAULT true,
	`techNotifyNewTickets` boolean DEFAULT true,
	`techNotifyCriticalAlerts` boolean DEFAULT true,
	`techNotifyMaintenanceReminders` boolean DEFAULT true,
	`techNotifyByEmail` boolean DEFAULT true,
	`techNotifyByPush` boolean DEFAULT true,
	`techDefaultView` varchar(20) DEFAULT 'dashboard',
	`techAutoRefreshLogs` boolean DEFAULT true,
	`techRefreshInterval` int DEFAULT 30,
	`techAvailableForEmergencies` boolean DEFAULT true,
	`techWorkingHoursStart` varchar(5) DEFAULT '08:00',
	`techWorkingHoursEnd` varchar(5) DEFAULT '18:00',
	`prefLanguage` varchar(10) DEFAULT 'es',
	`prefDistanceUnit` varchar(5) DEFAULT 'km',
	`prefCurrency` varchar(5) DEFAULT 'COP',
	`prefAutoLocate` boolean DEFAULT true,
	`prefSaveHistory` boolean DEFAULT true,
	`prefShareUsageData` boolean DEFAULT false,
	`twoFactorEnabled` boolean DEFAULT false,
	`twoFactorSecret` varchar(255),
	`twoFactorVerifiedAt` timestamp,
	`onboardingCompleted` boolean DEFAULT false,
	`onboardingStep` int DEFAULT 0,
	`onboardingStartedAt` timestamp,
	`onboardingCompletedAt` timestamp,
	`welcomeEmailSent` boolean DEFAULT false,
	`notifyProximity` boolean DEFAULT true,
	`proximityRadiusKm` int DEFAULT 5,
	`lastProximityAlertAt` timestamp,
	`lastProximityStationId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`),
	CONSTRAINT `users_email_unique` UNIQUE(`email`),
	CONSTRAINT `users_idTag_unique` UNIQUE(`idTag`)
);
--> statement-breakpoint
CREATE TABLE `wallet_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`walletId` int NOT NULL,
	`userId` int NOT NULL,
	`type` varchar(50) NOT NULL,
	`amount` decimal(12,2) NOT NULL,
	`balanceBefore` decimal(12,2) NOT NULL,
	`balanceAfter` decimal(12,2) NOT NULL,
	`referenceId` int,
	`referenceType` varchar(50),
	`payment_status` enum('PENDING','COMPLETED','FAILED','REFUNDED') NOT NULL DEFAULT 'PENDING',
	`description` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `wallet_transactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `wallets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`balance` decimal(12,2) NOT NULL DEFAULT '0',
	`currency` varchar(3) NOT NULL DEFAULT 'COP',
	`creditLimit` decimal(12,2) DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `wallets_id` PRIMARY KEY(`id`),
	CONSTRAINT `wallets_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `wompi_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`wompiTransactionId` varchar(255),
	`reference` varchar(255) NOT NULL,
	`amountInCents` bigint NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'COP',
	`wompi_tx_status` enum('PENDING','APPROVED','DECLINED','VOIDED','ERROR') NOT NULL DEFAULT 'PENDING',
	`wompi_tx_type` enum('WALLET_RECHARGE','SUBSCRIPTION','INVESTMENT_DEPOSIT','OTHER') NOT NULL,
	`paymentMethodType` varchar(50),
	`customerEmail` varchar(320),
	`description` text,
	`integritySignature` text,
	`processedAt` timestamp,
	`webhookReceivedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `wompi_transactions_id` PRIMARY KEY(`id`),
	CONSTRAINT `wompi_transactions_wompiTransactionId_unique` UNIQUE(`wompiTransactionId`),
	CONSTRAINT `wompi_transactions_reference_unique` UNIQUE(`reference`)
);
--> statement-breakpoint
ALTER TABLE `soc_accuracy_log` ADD CONSTRAINT `soc_accuracy_log_userId_users_id_fk` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `soc_accuracy_log` ADD CONSTRAINT `soc_accuracy_log_transactionId_transactions_id_fk` FOREIGN KEY (`transactionId`) REFERENCES `transactions`(`id`) ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `soc_accuracy_log` ADD CONSTRAINT `soc_accuracy_log_vehicleId_user_vehicles_id_fk` FOREIGN KEY (`vehicleId`) REFERENCES `user_vehicles`(`id`) ON DELETE set null ON UPDATE no action;