CREATE TABLE `banner_views` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`bannerId` int NOT NULL,
	`userId` int NOT NULL,
	`viewedAt` timestamp NOT NULL DEFAULT (now()),
	`clicked` boolean DEFAULT false,
	`clickedAt` timestamp,
	`viewContext` varchar(50),
	`sessionId` varchar(100),
	`deviceType` varchar(50),
	CONSTRAINT `banner_views_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `banners` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`subtitle` varchar(500),
	`description` text,
	`imageUrl` text NOT NULL,
	`imageUrlMobile` text,
	`banner_type` enum('SPLASH','CHARGING','MAP','PROMOTIONAL','INFORMATIONAL') NOT NULL,
	`linkUrl` text,
	`linkType` varchar(50),
	`linkTarget` varchar(50),
	`ctaText` varchar(100),
	`startDate` timestamp,
	`endDate` timestamp,
	`targetRoles` json,
	`targetCities` json,
	`targetSubscriptionTiers` json,
	`priority` int NOT NULL DEFAULT 0,
	`displayDurationMs` int DEFAULT 5000,
	`isClosable` boolean DEFAULT true,
	`showOnce` boolean DEFAULT false,
	`banner_status` enum('DRAFT','ACTIVE','PAUSED','EXPIRED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
	`impressions` int NOT NULL DEFAULT 0,
	`clicks` int NOT NULL DEFAULT 0,
	`uniqueViews` int NOT NULL DEFAULT 0,
	`advertiserName` varchar(255),
	`advertiserContact` varchar(255),
	`campaignId` varchar(100),
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `banners_id` PRIMARY KEY(`id`)
);
