CREATE TABLE `platform_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyName` varchar(255) DEFAULT 'Green House Project',
	`businessLine` varchar(255) DEFAULT 'Green EV',
	`nit` varchar(50),
	`contactEmail` varchar(255),
	`investorPercentage` int NOT NULL DEFAULT 80,
	`platformFeePercentage` int NOT NULL DEFAULT 20,
	`stripePublicKey` text,
	`stripeSecretKey` text,
	`stripeWebhookSecret` text,
	`stripeTestMode` boolean NOT NULL DEFAULT true,
	`enableEnergyBilling` boolean NOT NULL DEFAULT true,
	`enableReservationBilling` boolean NOT NULL DEFAULT true,
	`enableOccupancyPenalty` boolean NOT NULL DEFAULT true,
	`notifyChargeComplete` boolean NOT NULL DEFAULT true,
	`notifyReservationReminder` boolean NOT NULL DEFAULT true,
	`notifyPromotions` boolean NOT NULL DEFAULT false,
	`upmeEndpoint` text,
	`upmeToken` text,
	`upmeAutoReport` boolean NOT NULL DEFAULT true,
	`ocppPort` int DEFAULT 9000,
	`ocppServerActive` boolean NOT NULL DEFAULT true,
	`updatedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `platform_settings_id` PRIMARY KEY(`id`)
);
