CREATE TABLE `maintenance_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scheduleId` int NOT NULL,
	`stationId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`maintenanceType` varchar(100) NOT NULL,
	`dueDate` timestamp NOT NULL,
	`scheduledDate` timestamp,
	`completedDate` timestamp,
	`assignedTechnicianId` int,
	`maintenance_task_status` enum('pending','in_progress','completed','overdue','cancelled') NOT NULL DEFAULT 'pending',
	`completionNotes` text,
	`actualCostCop` bigint DEFAULT 0,
	`fundRecordId` int,
	`qualityRating` int,
	`ratingNotes` text,
	`ratedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `maintenance_tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `scheduled_maintenances` (
	`id` int AUTO_INCREMENT NOT NULL,
	`stationId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`maintenanceType` varchar(100) NOT NULL,
	`maintenance_frequency` enum('weekly','biweekly','monthly','quarterly','semiannual','annual','one_time') NOT NULL,
	`nextDueDate` timestamp NOT NULL,
	`lastCompletedDate` timestamp,
	`preferredTimeStart` varchar(5) NOT NULL DEFAULT '08:00',
	`preferredTimeEnd` varchar(5) NOT NULL DEFAULT '17:00',
	`assignedTechnicianId` int,
	`assignedEngineerId` int,
	`estimatedCostCop` bigint DEFAULT 0,
	`reminderDaysBefore` int NOT NULL DEFAULT 3,
	`reminderSent` boolean NOT NULL DEFAULT false,
	`maintenance_schedule_status` enum('active','paused','completed','cancelled') NOT NULL DEFAULT 'active',
	`notes` text,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scheduled_maintenances_id` PRIMARY KEY(`id`)
);
