CREATE TABLE `backup_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`backup_type` enum('FULL','CRITICAL','FINANCIAL','USERS','MANUAL') NOT NULL,
	`backup_status` enum('RUNNING','COMPLETED','FAILED','PARTIAL') NOT NULL DEFAULT 'RUNNING',
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`tablesIncluded` json,
	`totalRows` int DEFAULT 0,
	`totalSizeBytes` bigint DEFAULT 0,
	`s3Url` text,
	`s3Key` varchar(500),
	`errorMessage` text,
	`errorDetails` json,
	`triggeredBy` varchar(100) DEFAULT 'system',
	`isAutomatic` boolean NOT NULL DEFAULT true,
	`expiresAt` timestamp,
	`isDeleted` boolean NOT NULL DEFAULT false,
	`notes` text,
	CONSTRAINT `backup_logs_id` PRIMARY KEY(`id`)
);
