CREATE TABLE `chargers_catalog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(100) NOT NULL,
	`powerKw` decimal(8,2) NOT NULL,
	`charge_type` enum('AC','DC') NOT NULL,
	`connectorType` varchar(50) NOT NULL,
	`price` bigint NOT NULL,
	`description` text,
	`features` json,
	`imageUrl` text,
	`includesTransformer` boolean DEFAULT false,
	`cableMetersIncluded` int DEFAULT 10,
	`warrantyYears` int DEFAULT 2,
	`isActive` boolean NOT NULL DEFAULT true,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `chargers_catalog_id` PRIMARY KEY(`id`),
	CONSTRAINT `chargers_catalog_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `quote_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quoteId` int NOT NULL,
	`catalogItemId` int NOT NULL,
	`productName` varchar(255) NOT NULL,
	`productPowerKw` decimal(8,2) NOT NULL,
	`productChargeType` varchar(10) NOT NULL,
	`productConnector` varchar(50) NOT NULL,
	`unitPrice` bigint NOT NULL,
	`quantity` int NOT NULL DEFAULT 1,
	`lineTotal` bigint NOT NULL,
	`includesTransformer` boolean DEFAULT false,
	`cableMetersIncluded` int DEFAULT 10,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `quote_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `quote_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`validityDays` int NOT NULL DEFAULT 30,
	`evgreenFeePercent` int NOT NULL DEFAULT 30,
	`ownerSharePercent` int NOT NULL DEFAULT 70,
	`companyName` varchar(255) NOT NULL DEFAULT 'EVGreen - Green House Project S.A.S',
	`companyNit` varchar(50) NOT NULL DEFAULT '901.447.678-0',
	`companyPhone` varchar(50) NOT NULL DEFAULT '321 456 7644',
	`companyEmail` varchar(255) NOT NULL DEFAULT 'evgreen@greenhproject.com',
	`companyWebsite` varchar(255) NOT NULL DEFAULT 'www.evgreen.lat',
	`headerMessage` text,
	`footerMessage` text,
	`termsAndConditions` text,
	`exclusions` text,
	`benefitsDescription` text,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quote_settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quoteNumber` varchar(20) NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientEmail` varchar(320) NOT NULL,
	`clientPhone` varchar(50),
	`clientCompany` varchar(255),
	`clientCity` varchar(100),
	`advisorId` int NOT NULL,
	`advisorName` varchar(255),
	`quote_status` enum('DRAFT','SENT','VIEWED','ACCEPTED','REJECTED','EXPIRED') NOT NULL DEFAULT 'DRAFT',
	`subtotal` bigint NOT NULL DEFAULT 0,
	`discount` bigint DEFAULT 0,
	`total` bigint NOT NULL DEFAULT 0,
	`validityDays` int NOT NULL DEFAULT 30,
	`expiresAt` timestamp,
	`internalNotes` text,
	`clientNotes` text,
	`publicToken` varchar(64) NOT NULL,
	`viewedAt` timestamp,
	`viewCount` int DEFAULT 0,
	`sentAt` timestamp,
	`acceptedAt` timestamp,
	`rejectedAt` timestamp,
	`pdfUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quotes_id` PRIMARY KEY(`id`),
	CONSTRAINT `quotes_quoteNumber_unique` UNIQUE(`quoteNumber`),
	CONSTRAINT `quotes_publicToken_unique` UNIQUE(`publicToken`)
);
