ALTER TABLE `platform_settings`
  ADD COLUMN `docusign_environment` enum('SANDBOX','PRODUCTION') NOT NULL DEFAULT 'SANDBOX',
  ADD COLUMN `docusign_enabled` tinyint NOT NULL DEFAULT 0,
  ADD COLUMN `docusign_integration_key` varchar(100),
  ADD COLUMN `docusign_user_id` varchar(100),
  ADD COLUMN `docusign_account_id` varchar(100),
  ADD COLUMN `docusign_base_uri` varchar(255),
  ADD COLUMN `docusign_private_key_encrypted` text,
  ADD COLUMN `docusign_webhook_secret_encrypted` text,
  ADD COLUMN `docusign_last_test_at` timestamp NULL,
  ADD COLUMN `docusign_last_test_status` enum('NEVER','SUCCESS','FAILED') NOT NULL DEFAULT 'NEVER',
  ADD COLUMN `docusign_last_test_message` text;

CREATE TABLE `contract_templates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `version` varchar(64) NOT NULL,
  `status` enum('DRAFT','ACTIVE','RETIRED') NOT NULL DEFAULT 'DRAFT',
  `source_filename` varchar(255) NOT NULL,
  `source_mime_type` varchar(100) NOT NULL,
  `source_file_url` text NOT NULL,
  `source_file_key` varchar(500) NOT NULL,
  `html_content` longtext NOT NULL,
  `variable_schema` json NOT NULL,
  `content_hash` varchar(64) NOT NULL,
  `legal_review_note` text,
  `approved_by` int,
  `approved_at` timestamp NULL,
  `retired_by` int,
  `retired_at` timestamp NULL,
  `created_by` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `contract_templates_name_version_unique` (`name`,`version`),
  KEY `idx_contract_templates_status` (`status`,`created_at`)
);

CREATE TABLE `site_contracts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `contract_number` varchar(64) NOT NULL,
  `submission_id` int NOT NULL,
  `template_id` int NOT NULL,
  `template_name` varchar(255) NOT NULL,
  `template_version` varchar(64) NOT NULL,
  `status` enum('DRAFT','READY','DOCUSIGN_SENT','DOCUSIGN_COMPLETED','DOCUSIGN_DECLINED','DOCUSIGN_VOIDED','DOCUSIGN_EXPIRED','MANUAL_PDF_ISSUED','MANUAL_PDF_RETURNED','MANUAL_PDF_VERIFIED','MANUAL_PDF_REJECTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  `variables_snapshot` json NOT NULL,
  `contract_html` longtext NOT NULL,
  `content_hash` varchar(64) NOT NULL,
  `draft_pdf_url` text,
  `draft_pdf_key` varchar(500),
  `docusign_envelope_id` varchar(100),
  `docusign_envelope_status` varchar(64),
  `docusign_completed_pdf_url` text,
  `docusign_completed_pdf_key` varchar(500),
  `docusign_certificate_url` text,
  `docusign_certificate_key` varchar(500),
  `manual_signed_pdf_url` text,
  `manual_signed_pdf_key` varchar(500),
  `manual_returned_at` timestamp NULL,
  `manual_verified_at` timestamp NULL,
  `manual_verified_by` int,
  `expires_at` timestamp NULL,
  `issued_at` timestamp NULL,
  `completed_at` timestamp NULL,
  `cancelled_at` timestamp NULL,
  `cancelled_by` int,
  `cancellation_reason` text,
  `created_by` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `site_contracts_number_unique` (`contract_number`),
  UNIQUE KEY `site_contracts_docusign_envelope_unique` (`docusign_envelope_id`),
  KEY `idx_site_contracts_submission` (`submission_id`,`created_at`),
  KEY `idx_site_contracts_status` (`status`,`updated_at`)
);

CREATE TABLE `site_contract_parties` (
  `id` int NOT NULL AUTO_INCREMENT,
  `contract_id` int NOT NULL,
  `role` enum('OPERATOR','ALLY') NOT NULL,
  `legal_name` varchar(255) NOT NULL,
  `tax_id` varchar(64) NOT NULL,
  `representative_name` varchar(255) NOT NULL,
  `representative_document` varchar(64) NOT NULL,
  `representative_title` varchar(120),
  `email` varchar(320) NOT NULL,
  `phone` varchar(50),
  `notification_address` varchar(500) NOT NULL,
  `domicile` varchar(160),
  `signing_order` int NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `site_contract_parties_contract_role_unique` (`contract_id`,`role`),
  KEY `idx_site_contract_parties_contract_order` (`contract_id`,`signing_order`)
);

CREATE TABLE `site_contract_events` (
  `id` int NOT NULL AUTO_INCREMENT,
  `contract_id` int NOT NULL,
  `event_type` varchar(80) NOT NULL,
  `channel` enum('INTERNAL','DOCUSIGN','MANUAL_PDF') NOT NULL DEFAULT 'INTERNAL',
  `external_event_id` varchar(160),
  `actor_user_id` int,
  `actor_role` varchar(32),
  `actor_email` varchar(320),
  `ip_address` varchar(64),
  `user_agent` text,
  `details` json,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `site_contract_events_external_unique` (`external_event_id`),
  KEY `idx_site_contract_events_contract_created` (`contract_id`,`created_at`)
);
