CREATE TABLE `space_photos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`submissionId` int NOT NULL,
	`photoUrl` text NOT NULL,
	`photoKey` varchar(500) NOT NULL,
	`caption` varchar(255),
	`photo_type` enum('general','electrical_panel','transformer','parking_area','access_road','surroundings','other') NOT NULL DEFAULT 'general',
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `space_photos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `space_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(20) NOT NULL,
	`submitterName` varchar(255) NOT NULL,
	`submitterEmail` varchar(320) NOT NULL,
	`submitterPhone` varchar(20) NOT NULL,
	`submitterCompany` varchar(255),
	`submitterDocument` varchar(50),
	`spaceName` varchar(255) NOT NULL,
	`space_type` enum('parking','mall','gas_station','hotel','restaurant','office_building','residential','supermarket','hospital','university','airport','highway_rest','other') NOT NULL,
	`spaceTypeOther` varchar(255),
	`address` varchar(500) NOT NULL,
	`city` varchar(100) NOT NULL,
	`department` varchar(100),
	`country` varchar(100) NOT NULL DEFAULT 'Colombia',
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`availableAreaM2` decimal(10,2),
	`parkingSpots` int,
	`transformerCapacityKva` decimal(10,2),
	`hasElectricalPanel` boolean DEFAULT false,
	`electricalDistance` int,
	`hasInternet` boolean DEFAULT false,
	`operatingHoursStart` varchar(5) DEFAULT '06:00',
	`operatingHoursEnd` varchar(5) DEFAULT '22:00',
	`is24Hours` boolean DEFAULT false,
	`estimatedDailyVehicles` int,
	`estimatedEvPercent` int,
	`nearbyAttractions` text,
	`socioeconomicStratum` int,
	`additionalNotes` text,
	`space_status` enum('pending','under_review','approved','rejected','letter_sent','letter_accepted','published','funded','in_construction','operational') NOT NULL DEFAULT 'pending',
	`technicalScore` int,
	`technicalNotes` text,
	`electrical_viability` enum('viable','requires_upgrade','not_viable'),
	`accessibilityScore` int,
	`trafficPotentialScore` int,
	`evaluatedBy` int,
	`evaluatedAt` timestamp,
	`rejectionReason` text,
	`aiScore` int,
	`aiAnalysis` text,
	`aiScoredAt` timestamp,
	`letterSentAt` timestamp,
	`letterAcceptedAt` timestamp,
	`letterToken` varchar(100),
	`letterSignerName` varchar(255),
	`letterSignerDocument` varchar(50),
	`letterSignerIp` varchar(50),
	`crowdfundingProjectId` int,
	`estimatedInvestmentCop` bigint,
	`estimatedPowerKw` int,
	`estimatedChargerCount` int,
	`recommendedChargerType` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `space_submissions_id` PRIMARY KEY(`id`),
	CONSTRAINT `space_submissions_code_unique` UNIQUE(`code`)
);
