ALTER TABLE `users` ADD COLUMN `siigo_customer_id` varchar(100) NULL;
ALTER TABLE `users` ADD COLUMN `world_office_customer_id` varchar(100) NULL;

CREATE TABLE IF NOT EXISTS `tenant_billing_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organization_id` int NULL,
	`billing_provider` enum('alegra','siigo','world_office') NOT NULL DEFAULT 'alegra',
	`enabled` tinyint NOT NULL DEFAULT 0,
	`billing_environment` enum('sandbox','production') NOT NULL DEFAULT 'production',
	`auto_invoice` tinyint NOT NULL DEFAULT 1,
	`auto_send_email` tinyint NOT NULL DEFAULT 1,
	`resolution_number` varchar(100) NULL,
	`alegra_email` varchar(255) NULL,
	`alegra_token` text NULL,
	`alegra_default_item_id` varchar(50) NULL,
	`alegra_default_tax_id` varchar(50) NULL,
	`alegra_payment_method_id` varchar(50) NULL,
	`alegra_payment_account_id` varchar(50) NULL,
	`alegra_use_electronic_stamp` tinyint NOT NULL DEFAULT 1,
	`siigo_username` varchar(255) NULL,
	`siigo_access_key` text NULL,
	`siigo_partner_id` varchar(100) NULL,
	`siigo_document_id` varchar(50) NULL,
	`siigo_seller_id` varchar(50) NULL,
	`siigo_payment_type_id` varchar(50) NULL,
	`siigo_product_code` varchar(100) NULL,
	`siigo_tax_id` varchar(50) NULL,
	`siigo_stamp` tinyint NOT NULL DEFAULT 1,
	`siigo_mail` tinyint NOT NULL DEFAULT 1,
	`world_office_token` text NULL,
	`world_office_company_id` varchar(50) NULL,
	`world_office_document_type_id` varchar(50) NULL,
	`world_office_prefix_id` varchar(50) NULL,
	`world_office_payment_method_id` varchar(50) NULL,
	`world_office_item_id` varchar(50) NULL,
	`world_office_tax_id` varchar(50) NULL,
	`billing_last_test_status` enum('none','success','error') NOT NULL DEFAULT 'none',
	`last_test_message` text NULL,
	`last_tested_at` timestamp NULL,
	`updated_by` int NULL,
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tenant_billing_settings_id` PRIMARY KEY(`id`),
	INDEX `idx_tenant_billing_org` (`organization_id`)
);

CREATE TABLE IF NOT EXISTS `electronic_invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organization_id` int NULL,
	`transaction_id` int NOT NULL,
	`electronic_invoice_provider` enum('alegra','siigo','world_office') NOT NULL,
	`electronic_invoice_status` enum('PENDING','PROCESSING','COMPLETED','FAILED','RETRYABLE_ERROR') NOT NULL DEFAULT 'PENDING',
	`external_invoice_id` varchar(100) NULL,
	`invoice_number` varchar(100) NULL,
	`cufe` text NULL,
	`total_amount` decimal(12, 2) NOT NULL DEFAULT 0.00,
	`energy_kwh` decimal(10, 4) NOT NULL DEFAULT 0.0000,
	`customer_name` varchar(255) NULL,
	`customer_identification` varchar(50) NULL,
	`customer_email` varchar(255) NULL,
	`external_contact_id` varchar(100) NULL,
	`pdf_url` text NULL,
	`xml_url` text NULL,
	`error_message` text NULL,
	`attempts` int NOT NULL DEFAULT 0,
	`last_attempt_at` timestamp NULL,
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `electronic_invoices_id` PRIMARY KEY(`id`),
	INDEX `idx_elec_inv_org` (`organization_id`),
	INDEX `idx_elec_inv_tx` (`transaction_id`)
);
